export const PROJECT_LIST = [
    {
        id: 'hot-now',
        image: '/projects/hot-now.jpg',
        url: 'https://hotnow.garylin.dev/',
        name: 'Hot Now',
        tags: [
            '2025',
            'Next.js',
            'TypeScript',
            'Tailwind CSS',
            'Shadcn UI',
            'Zustand',
            'TanStack Query',
            'React Hook Form',
            'Zod',
            'Google Analytics',
            'Puppeteer',
            'next-themes',
        ],
    },
    {
        id: 'life-restart',
        image: '/projects/life-restart.jpg',
        url: 'https://garylin0969-life-restart.vercel.app/',
        name: '人生重來 - Life Restart',
        tags: ['2025', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Shadcn UI', 'next-intl', 'next-themes'],
    },
    {
        id: 'perplexity-ai-concat',
        image: '/projects/perplexity-ai-concat.jpg',
        url: 'https://garylin0969-perplexity-concat.vercel.app/',
        name: 'AI 串接測試工具 - Perplexity AI Concat',
        tags: ['2025', 'Perplexity API', 'React', 'TypeScript', 'Tailwind CSS', 'React Hook Form', 'React Json View'],
    },
    {
        id: 'gemini-api-tester',
        image: '/projects/gemini-api-tester.jpg',
        url: 'https://garylin0969-gemini-tester.vercel.app/',
        name: 'AI 串接測試工具 - Gemini API Tester',
        tags: ['2025', 'Gemini', 'Next', 'TypeScript', 'Tailwind CSS', 'Shadcn UI', 'React Query'],
    },
    {
        id: 'blog',
        image: '/projects/blog.jpg',
        url: 'https://github.com/garylin0969/blog',
        name: 'Blog - GaryLin.dev',
        tags: [
            '2024',
            'Next.js',
            'TypeScript',
            'Google Analytics',
            'Contentlayer',
            'Tailwind CSS',
            'next-themes',
            'Giscus',
        ],
    },
    {
        id: 'chinese-number-format',
        image: '/projects/chinese-number-format.avif',
        url: 'https://www.npmjs.com/package/chinese-number-format',
        name: 'NPM 套件 - chinese-number-format',
        tags: ['2024', 'TypeScript', 'Jest', 'NPM'],
    },
    {
        id: 'next13-imdb-clone',
        image: '/projects/next13-imdb-clone.avif',
        url: 'https://garylin0969-next-imdb-clone.vercel.app',
        name: 'Clone - IMDb',
        tags: ['2023', 'Next.js', 'TypeScript', 'React Hook Form', 'SWR', 'Tailwind CSS', 'next-themes'],
    },
    {
        id: 'next13-google-clone',
        image: '/projects/next13-google-clone.avif',
        url: 'https://garylin0969-next-google-clone.vercel.app',
        name: 'Clone - Google',
        tags: ['2023', 'Next.js', 'TypeScript', 'React Hook Form', 'SWR', 'Tailwind CSS'],
    },
    {
        id: 'akatsuki',
        image: '/projects/akatsuki.avif',
        url: 'https://garylin0969-akatsuki.vercel.app',
        name: '火影忍者 - 曉組織成員介紹',
        tags: ['2023', 'React.js', 'Redux', 'TypeScript', 'Styled Components'],
    },
    {
        id: 'ispan-project',
        image: '/projects/ispan-project.jpg',
        url: 'https://github.com/garylin0969/react-ispan-project',
        name: 'iSpan 資策會 - 專題',
        tags: ['2022', 'React.js', 'JavaScript', 'Socket.IO', 'Bootstrap', 'GSAP'],
    },
];
