const experienceConfig = [
    {
        id: 'anue',
        logoSrc: '/assets/company-logo/anue.png',
        title: 'Frontend Developer',
        companyUrl: 'https://www.cnyes.com/',
        companyName: 'Anue 鉅亨網',
        employmentStartDate: '2024.03',
        employmentEndDate: 'Now',
        button: {
            enabled: true,
            text: 'More details',
        },
        details: [
            '參與 Scrum 開發流程，運用 Jira、Slack 與 Confluence 促進跨部門協作及專案管理。',
            '負責外匯及新聞領域專案的開發，涵蓋約 10 項專案的功能維護與新增需求。',
            '採用 Docker 將網站封裝為映像檔，結合 GitLab CI/CD 部署至 GitLab Container Registry。',
            '利用 Highcharts 與 TradingView 開發動態視覺化圖表，提供精確數據呈現。',
            '透過 Google Analytics (GA4) 收集並分析用戶行為數據，生成深度洞察報告。',
            '結合 Next.js、伺服端渲染 (SSR) 及 Metadata 優化，有效提升網站 SEO 表現。',
            '實現 Lazy Load 機制，顯著優化網頁效能與載入速度。',
            '採用 React Query 與快取技術，降低 API 呼叫次數並提升前端運行效率。',
            '運用 React.js、TypeScript、Tailwind CSS 及 Vite 開發 B2B 專案平台。',
            '公司技術涵蓋（但不限於） Next.js、TypeScript、Tailwind CSS、React Query、Jest、Storybook、Google Analytics 及 TradingView。',
        ],
    },
    {
        id: 'uec',
        logoSrc: '/assets/company-logo/uec.jpg',
        title: 'Frontend Developer',
        companyUrl: 'https://www.universalec.com/',
        companyName: 'Universal EC Inc.',
        employmentStartDate: '2022.10',
        employmentEndDate: '2024.02',
        button: {
            enabled: true,
            text: 'More details',
        },
        details: [
            '參與 Scrum 敏捷開發流程，運用 Mantis 與 Asana 進行跨部門協作及專案管理。',
            '重構系統架構，導入 Prettier、JWT 與 Jest 等技術，以顯著提升程式碼品質與系統效能。',
            '深入研究 Next.js 技術，應用於前台系統的升級及新功能開發，推動技術革新。',
            '優化既有專案架構，實現元件化設計，有效降低重工成本並增強程式維護性。',
            '建構 GitLab CI/CD 自動化部署流程。',
            '支援電子發票加值中心專案的全周期開發與維護工作。',
            '主導模板專案系統架構的重構與優化，提升整體系統穩定性。',
            '參與財團法人純青社會福利基金會學堂管理系統的開發與運營維護。',
            '領導簽審通關共同作業平台前後台系統的整合開發，確保系統協同運作。',
            '參與第一社會福利基金會捐款管理系統的設計與開發，優化捐款流程。',
            '利用 React Bootstrap 完成前端 UI 樣式的設計與實現，確保視覺一致性。',
            '通過 Sourcetree、GitLab 與 Apache 有效管理版本控制及部署流程。',
            '採用 Spring Boot 開發後端系統，並使用 MS SQL 與 Oracle 進行資料庫管理。',
            '使用 React.js 、Next.js、TypeScript、React Hook Form、Redux、Axios 與 Jest 實現前端開發。',
        ],
    },
    {
        id: 'ispan',
        logoSrc: '/assets/company-logo/ispan.png',
        title: 'Frontend Class Trainee',
        companyUrl: 'https://www.ispan.com.tw/',
        companyName: 'iSpan International Inc.',
        employmentStartDate: '2022.03',
        employmentEndDate: '2022.08',
        button: {
            enabled: true,
            text: 'More details',
        },
        details: [
            '實施 JSON Web Token (JWT) 與 Google OAuth 認證機制。',
            '開發會員中心及收藏功能，提供完善的用戶資料管理與個性化服務，優化用戶體驗。',
            '整合 Socket.IO 架構聊天室，實現用戶間即時的通訊互動。',
            '採用 Chart.js 構建數據可視化報表，提升資料呈現效果並增強數據分析能力。',
            '基於 React.js 搭配 Axios 進行 API 整合，運用 Bootstrap 與 MUI 完成前端設計，並結合 GSAP 強化頁面動畫效果，打造流暢互動介面。',
            '採用 Express 框架搭建後端伺服器，並以 MySQL 作為資料庫管理系統。',
        ],
    },
];

export default experienceConfig;
