const projectsConfig = [
    {
        id: 'hot-now',
        imageUrl: '/assets/projects/hot-now.jpg',
        projectUrl: 'https://hotnow.garylin.dev/',
        projectName: 'Hot Now',
        projectTags: [
            '2025',
            'Next',
            'TypeScript',
            'Tailwind CSS',
            'Shadcn UI',
            'Zustand',
            'TanStack Query',
            'React Hook Form',
            'Zod',
            'Google Analytics',
            'Puppeteer',
            'next-themes',
        ],
    },
    {
        id: 'life-restart',
        imageUrl: '/assets/projects/life-restart.jpg',
        projectUrl: 'https://garylin0969-life-restart.vercel.app/',
        projectName: '人生重來 - Life Restart',
        projectTags: ['2025', 'Next', 'TypeScript', 'Tailwind CSS', 'Shadcn UI', 'next-intl', 'next-themes'],
    },
    {
        id: 'perplexity-ai-concat',
        imageUrl: '/assets/projects/perplexity-ai-concat.jpg',
        projectUrl: 'https://garylin0969-perplexity-concat.vercel.app/',
        projectName: 'AI 串接測試工具 - Perplexity AI Concat',
        projectTags: [
            '2025',
            'Perplexity API',
            'React',
            'TypeScript',
            'Tailwind CSS',
            'React Hook Form',
            'React Json View',
        ],
    },
    {
        id: 'gemini-api-tester',
        imageUrl: '/assets/projects/gemini-api-tester.jpg',
        projectUrl: 'https://garylin0969-gemini-tester.vercel.app/',
        projectName: 'AI 串接測試工具 - Gemini API Tester',
        projectTags: ['2025', 'Gemini', 'Next', 'TypeScript', 'Tailwind CSS', 'Shadcn UI', 'React Query'],
    },
    {
        id: 'blog',
        imageUrl: '/assets/projects/blog.jpg',
        projectUrl: 'https://github.com/garylin0969/blog',
        projectName: 'Blog - GaryLin.dev',
        projectTags: [
            '2024',
            'Next',
            'TypeScript',
            'Google Analytics',
            'Contentlayer',
            'Tailwind CSS',
            'next-themes',
            'Giscus',
        ],
    },
    {
        id: 'chinese-number-format',
        imageUrl: '/assets/projects/chinese-number-format.avif',
        projectUrl: 'https://www.npmjs.com/package/chinese-number-format',
        projectName: 'NPM 套件 - chinese-number-format',
        projectTags: ['2024', 'TypeScript', 'Jest', 'NPM'],
    },
    {
        id: 'next13-imdb-clone',
        imageUrl: '/assets/projects/next13-imdb-clone.avif',
        projectUrl: 'https://garylin0969-next-imdb-clone.vercel.app',
        projectName: 'Clone - IMDb',
        projectTags: ['2023', 'Next', 'TypeScript', 'React Hook Form', 'SWR', 'Tailwind CSS', 'next-themes'],
    },
    {
        id: 'next13-google-clone',
        imageUrl: '/assets/projects/next13-google-clone.avif',
        projectUrl: 'https://garylin0969-next-google-clone.vercel.app',
        projectName: 'Clone - Google',
        projectTags: ['2023', 'Next', 'TypeScript', 'React Hook Form', 'SWR', 'Tailwind CSS'],
    },
    {
        id: 'akatsuki',
        imageUrl: '/assets/projects/akatsuki.avif',
        projectUrl: 'https://garylin0969-akatsuki.vercel.app',
        projectName: '火影忍者 - 曉組織成員介紹',
        projectTags: ['2023', 'React', 'Redux', 'TypeScript', 'Styled Components'],
    },
    {
        id: 'ispan-project',
        imageUrl: '/assets/projects/ispan-project.jpg',
        projectUrl: 'https://github.com/garylin0969/react-ispan-project',
        projectName: 'iSpan 資策會 - 專題',
        projectTags: ['2022', 'React', 'JavaScript', 'Socket.IO', 'Bootstrap', 'GSAP'],
    },
];

export default projectsConfig;
